[package]
name = "py"
version.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
debug = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { workspace = true }
miette = { workspace = true }
pathdiff = "0.2.3"
relative-path = "1.9.3"
sha256 = "1.6.0"
tempfile = { workspace = true }
thiserror = { workspace = true }
uv-cache = { workspace = true }
uv-distribution-filename = { workspace = true }
uv-extract = { workspace = true }
uv-install-wheel = { workspace = true }
uv-pypi-types = { workspace = true }
uv-python = { workspace = true }
uv-virtualenv = { workspace = true }
walkdir = "2.5.0"
# workaround issue with this package building with rules_rust on windows; the snap files used in their unit tests have
# too long a path and import of this module is failing (even when tests are not run)
rattler_installs_packages = { git = "https://github.com/peakschris/rip", rev = "3de9ee95eab577c9e48526464013e217287c6937", default-features = false, features = ["rustls-tls"] }
