[project]
name = "aspect_rules_py"
version = "0.0.0"
authors = []
requires-python = ">=3.9, <3.12"
dependencies = [
   "setuptools",
   "build",
   "django~=4.2.7",
   "colorama~=0.4.0",
   "click",
   "pytest",
   "coverage",
   "cowsay",
   "snakesay",
   "ftfy==6.2.0",
   "neptune==1.10.2",
   "six",
   "bazel-runfiles",
   "maturin",
]
