[project]
name = "workspace"
version = "0.0.0"
dependencies = []

[tool.uv.sources]
workspace = { workspace = true }
foo = { workspace = true }
pi = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
