[project]
name = "googlemaps-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = ["build>=1.3.0", "googlemaps>=4.10.0", "setuptools>=80.9.0"]

[build-system]
requires = ["build>=1.3.0", "setuptools>=80.9.0"]

[tool.uv.extra-build-dependencies]
googlemaps = ["build", "setuptools"]

# [[tool.uv.dependency-metadata]]
# name = "googlemaps"
# requires-dist = ["build", "setuptools", "requests"]
